from pydantic import BaseModel

class PlanningState(BaseModel):
    """
    Represents the planning state of an AI engine.

    Attributes:
        user_goal (str): The goal specified by the user.
        intent (dict): The inferred intent of the user based on their input.
        constraints (dict): Any constraints or limitations that need to be considered during planning.
        candidates (list): A list of candidate plans generated by the AI engine.
        plans (list): A list of all possible plans considered by the AI engine.
        selected_plan (dict): The plan that has been selected for execution.
        evulation_results (dict): Results from evaluating the selected plan against the user's goal and constraints.

    """
    user_goal: str
    intent: dict
    constraints: dict
    candidates: list
    plans: list
    selected_plan: dict
    evulation_results: dict


